Watching for file changes with StatReloader
[19/Apr/2020 02:01:09] "GET /api/ HTTP/1.1" 200 8767
Watching for file changes with StatReloader
[19/Apr/2020 02:03:53] "GET /api/ HTTP/1.1" 200 8767
[19/Apr/2020 02:03:53] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[19/Apr/2020 02:03:53] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[19/Apr/2020 02:05:02] "GET /api/ HTTP/1.1" 200 36
[19/Apr/2020 02:06:23] "GET /api/ HTTP/1.1" 200 36
/workspace/20200415/django-back/backend/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2020 - 02:03:22
Django version 3.0.5, using settings 'backend.settings'
Starting development server at http://0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[19/Apr/2020 02:07:47] "GET /api/ HTTP/1.1" 200 8767
[19/Apr/2020 02:07:58] "GET /api/ HTTP/1.1" 200 36
Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 16, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
[19/Apr/2020 03:55:19] "GET /api/ HTTP/1.1" 200 36
Watching for file changes with StatReloader
[19/Apr/2020 03:56:31] "GET /api/ HTTP/1.1" 200 36
[19/Apr/2020 03:56:33] "GET /api/ HTTP/1.1" 200 8733
Watching for file changes with StatReloader
[19/Apr/2020 03:57:36] "GET /api/ HTTP/1.1" 200 8733
Watching for file changes with StatReloader
[19/Apr/2020 04:00:43] "GET /api/ HTTP/1.1" 200 36
